// @generated by tools/generate_reason_codes.py
// source: specs/status/status_reason_registries_manifest.json
// DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RejectReasonCode {
    #[serde(rename = "TOO_SMALL_AFTER_QUANTIZATION")]
    TooSmallAfterQuantization,

    #[serde(rename = "INSTRUMENT_METADATA_MISSING")]
    InstrumentMetadataMissing,

    #[serde(rename = "CHURN_BREAKER_ACTIVE")]
    ChurnBreakerActive,

    #[serde(rename = "LIQUIDITY_GATE_NO_L2")]
    LiquidityGateNoL2,

    #[serde(rename = "EMERGENCY_CLOSE_NO_PRICE")]
    EmergencyCloseNoPrice,

    #[serde(rename = "EXPECTED_SLIPPAGE_TOO_HIGH")]
    ExpectedSlippageTooHigh,

    #[serde(rename = "NET_EDGE_TOO_LOW")]
    NetEdgeTooLow,

    #[serde(rename = "NET_EDGE_INPUT_MISSING")]
    NetEdgeInputMissing,

    #[serde(rename = "PRICER_INPUT_MISSING")]
    PricerInputMissing,

    #[serde(rename = "PRICER_INPUT_INVALID")]
    PricerInputInvalid,

    #[serde(rename = "GATE_CASCADE_SKIP")]
    GateCascadeSkip,

    #[serde(rename = "INSUFFICIENT_DEPTH_WITHIN_BUDGET")]
    InsufficientDepthWithinBudget,

    #[serde(rename = "FEE_CACHE_STALE")]
    FeeCacheStale,

    #[serde(rename = "RECORDED_BEFORE_DISPATCH_FAILED")]
    RecordedBeforeDispatchFailed,

    #[serde(rename = "ASSEMBLY_FAILED")]
    AssemblyFailed,

    #[serde(rename = "INVENTORY_SKEW")]
    InventorySkew,

    #[serde(rename = "INVENTORY_SKEW_DELTA_LIMIT_MISSING")]
    InventorySkewDeltaLimitMissing,

    #[serde(rename = "PENDING_EXPOSURE_BUDGET_EXCEEDED")]
    PendingExposureBudgetExceeded,

    #[serde(rename = "GLOBAL_EXPOSURE_BUDGET_EXCEEDED")]
    GlobalExposureBudgetExceeded,

    #[serde(rename = "CONTRACTS_AMOUNT_MISMATCH")]
    ContractsAmountMismatch,

    #[serde(rename = "MARGIN_HEADROOM_REJECT_OPENS")]
    MarginHeadroomRejectOpens,

    #[serde(rename = "ORDER_TYPE_MARKET_FORBIDDEN")]
    OrderTypeMarketForbidden,

    #[serde(rename = "ORDER_TYPE_STOP_FORBIDDEN")]
    OrderTypeStopForbidden,

    #[serde(rename = "LINKED_ORDER_TYPE_FORBIDDEN")]
    LinkedOrderTypeForbidden,

    #[serde(rename = "POST_ONLY_WOULD_CROSS")]
    PostOnlyWouldCross,

    #[serde(rename = "RISK_INCREASING_CANCEL_REPLACE_FORBIDDEN")]
    RiskIncreasingCancelReplaceForbidden,

    #[serde(rename = "RATE_LIMIT_BROWNOUT")]
    RateLimitBrownout,

    #[serde(rename = "INSTRUMENT_EXPIRED_OR_DELISTED")]
    InstrumentExpiredOrDelisted,

    #[serde(rename = "FEEDBACK_LOOP_GUARD_ACTIVE")]
    FeedbackLoopGuardActive,

    #[serde(rename = "LABEL_TOO_LONG")]
    LabelTooLong,
}

impl RejectReasonCode {
    pub const ALL: &'static [Self] = &[
        Self::TooSmallAfterQuantization,
        Self::InstrumentMetadataMissing,
        Self::ChurnBreakerActive,
        Self::LiquidityGateNoL2,
        Self::EmergencyCloseNoPrice,
        Self::ExpectedSlippageTooHigh,
        Self::NetEdgeTooLow,
        Self::NetEdgeInputMissing,
        Self::PricerInputMissing,
        Self::PricerInputInvalid,
        Self::GateCascadeSkip,
        Self::InsufficientDepthWithinBudget,
        Self::FeeCacheStale,
        Self::RecordedBeforeDispatchFailed,
        Self::AssemblyFailed,
        Self::InventorySkew,
        Self::InventorySkewDeltaLimitMissing,
        Self::PendingExposureBudgetExceeded,
        Self::GlobalExposureBudgetExceeded,
        Self::ContractsAmountMismatch,
        Self::MarginHeadroomRejectOpens,
        Self::OrderTypeMarketForbidden,
        Self::OrderTypeStopForbidden,
        Self::LinkedOrderTypeForbidden,
        Self::PostOnlyWouldCross,
        Self::RiskIncreasingCancelReplaceForbidden,
        Self::RateLimitBrownout,
        Self::InstrumentExpiredOrDelisted,
        Self::FeedbackLoopGuardActive,
        Self::LabelTooLong,
    ];

    /// Contract token from the manifest.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::TooSmallAfterQuantization => "TooSmallAfterQuantization",
            Self::InstrumentMetadataMissing => "InstrumentMetadataMissing",
            Self::ChurnBreakerActive => "ChurnBreakerActive",
            Self::LiquidityGateNoL2 => "LiquidityGateNoL2",
            Self::EmergencyCloseNoPrice => "EmergencyCloseNoPrice",
            Self::ExpectedSlippageTooHigh => "ExpectedSlippageTooHigh",
            Self::NetEdgeTooLow => "NetEdgeTooLow",
            Self::NetEdgeInputMissing => "NetEdgeInputMissing",
            Self::PricerInputMissing => "PricerInputMissing",
            Self::PricerInputInvalid => "PricerInputInvalid",
            Self::GateCascadeSkip => "GateCascadeSkip",
            Self::InsufficientDepthWithinBudget => "InsufficientDepthWithinBudget",
            Self::FeeCacheStale => "FeeCacheStale",
            Self::RecordedBeforeDispatchFailed => "RecordedBeforeDispatchFailed",
            Self::AssemblyFailed => "AssemblyFailed",
            Self::InventorySkew => "InventorySkew",
            Self::InventorySkewDeltaLimitMissing => "InventorySkewDeltaLimitMissing",
            Self::PendingExposureBudgetExceeded => "PendingExposureBudgetExceeded",
            Self::GlobalExposureBudgetExceeded => "GlobalExposureBudgetExceeded",
            Self::ContractsAmountMismatch => "ContractsAmountMismatch",
            Self::MarginHeadroomRejectOpens => "MarginHeadroomRejectOpens",
            Self::OrderTypeMarketForbidden => "OrderTypeMarketForbidden",
            Self::OrderTypeStopForbidden => "OrderTypeStopForbidden",
            Self::LinkedOrderTypeForbidden => "LinkedOrderTypeForbidden",
            Self::PostOnlyWouldCross => "PostOnlyWouldCross",
            Self::RiskIncreasingCancelReplaceForbidden => "RiskIncreasingCancelReplaceForbidden",
            Self::RateLimitBrownout => "RateLimitBrownout",
            Self::InstrumentExpiredOrDelisted => "InstrumentExpiredOrDelisted",
            Self::FeedbackLoopGuardActive => "FeedbackLoopGuardActive",
            Self::LabelTooLong => "LabelTooLong",
        }
    }

    /// Current serde / wire representation.
    pub const fn wire_str(self) -> &'static str {
        match self {
            Self::TooSmallAfterQuantization => "TOO_SMALL_AFTER_QUANTIZATION",
            Self::InstrumentMetadataMissing => "INSTRUMENT_METADATA_MISSING",
            Self::ChurnBreakerActive => "CHURN_BREAKER_ACTIVE",
            Self::LiquidityGateNoL2 => "LIQUIDITY_GATE_NO_L2",
            Self::EmergencyCloseNoPrice => "EMERGENCY_CLOSE_NO_PRICE",
            Self::ExpectedSlippageTooHigh => "EXPECTED_SLIPPAGE_TOO_HIGH",
            Self::NetEdgeTooLow => "NET_EDGE_TOO_LOW",
            Self::NetEdgeInputMissing => "NET_EDGE_INPUT_MISSING",
            Self::PricerInputMissing => "PRICER_INPUT_MISSING",
            Self::PricerInputInvalid => "PRICER_INPUT_INVALID",
            Self::GateCascadeSkip => "GATE_CASCADE_SKIP",
            Self::InsufficientDepthWithinBudget => "INSUFFICIENT_DEPTH_WITHIN_BUDGET",
            Self::FeeCacheStale => "FEE_CACHE_STALE",
            Self::RecordedBeforeDispatchFailed => "RECORDED_BEFORE_DISPATCH_FAILED",
            Self::AssemblyFailed => "ASSEMBLY_FAILED",
            Self::InventorySkew => "INVENTORY_SKEW",
            Self::InventorySkewDeltaLimitMissing => "INVENTORY_SKEW_DELTA_LIMIT_MISSING",
            Self::PendingExposureBudgetExceeded => "PENDING_EXPOSURE_BUDGET_EXCEEDED",
            Self::GlobalExposureBudgetExceeded => "GLOBAL_EXPOSURE_BUDGET_EXCEEDED",
            Self::ContractsAmountMismatch => "CONTRACTS_AMOUNT_MISMATCH",
            Self::MarginHeadroomRejectOpens => "MARGIN_HEADROOM_REJECT_OPENS",
            Self::OrderTypeMarketForbidden => "ORDER_TYPE_MARKET_FORBIDDEN",
            Self::OrderTypeStopForbidden => "ORDER_TYPE_STOP_FORBIDDEN",
            Self::LinkedOrderTypeForbidden => "LINKED_ORDER_TYPE_FORBIDDEN",
            Self::PostOnlyWouldCross => "POST_ONLY_WOULD_CROSS",
            Self::RiskIncreasingCancelReplaceForbidden => "RISK_INCREASING_CANCEL_REPLACE_FORBIDDEN",
            Self::RateLimitBrownout => "RATE_LIMIT_BROWNOUT",
            Self::InstrumentExpiredOrDelisted => "INSTRUMENT_EXPIRED_OR_DELISTED",
            Self::FeedbackLoopGuardActive => "FEEDBACK_LOOP_GUARD_ACTIVE",
            Self::LabelTooLong => "LABEL_TOO_LONG",
        }
    }
}
