// @generated by tools/generate_reason_codes.py
// source: specs/status/status_reason_registries_manifest.json
// DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum TradingMode {
    #[serde(rename = "Active")]
    Active,

    #[serde(rename = "ReduceOnly")]
    ReduceOnly,

    #[serde(rename = "Kill")]
    Kill,
}

impl TradingMode {
    pub const ALL: &'static [Self] = &[
        Self::Active,
        Self::ReduceOnly,
        Self::Kill,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Active => "Active",
            Self::ReduceOnly => "ReduceOnly",
            Self::Kill => "Kill",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DeploymentEnvironment {
    #[serde(rename = "DEV")]
    Dev,

    #[serde(rename = "STAGING")]
    Staging,

    #[serde(rename = "PAPER")]
    Paper,

    #[serde(rename = "LIVE")]
    Live,
}

impl DeploymentEnvironment {
    pub const ALL: &'static [Self] = &[
        Self::Dev,
        Self::Staging,
        Self::Paper,
        Self::Live,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Dev => "DEV",
            Self::Staging => "STAGING",
            Self::Paper => "PAPER",
            Self::Live => "LIVE",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RiskState {
    #[serde(rename = "Healthy")]
    Healthy,

    #[serde(rename = "Degraded")]
    Degraded,

    #[serde(rename = "Maintenance")]
    Maintenance,
}

impl RiskState {
    pub const ALL: &'static [Self] = &[
        Self::Healthy,
        Self::Degraded,
        Self::Maintenance,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Healthy => "Healthy",
            Self::Degraded => "Degraded",
            Self::Maintenance => "Maintenance",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum F1CertState {
    #[serde(rename = "PASS")]
    Pass,

    #[serde(rename = "FAIL")]
    Fail,

    #[serde(rename = "STALE")]
    Stale,

    #[serde(rename = "MISSING")]
    Missing,

    #[serde(rename = "INVALID")]
    Invalid,
}

impl F1CertState {
    pub const ALL: &'static [Self] = &[
        Self::Pass,
        Self::Fail,
        Self::Stale,
        Self::Missing,
        Self::Invalid,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pass => "PASS",
            Self::Fail => "FAIL",
            Self::Stale => "STALE",
            Self::Missing => "MISSING",
            Self::Invalid => "INVALID",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[allow(clippy::enum_variant_names)]
pub enum ModeReasonCode {
    #[serde(rename = "KILL_WATCHDOG_HEARTBEAT_STALE")]
    KillWatchdogHeartbeatStale,

    #[serde(rename = "KILL_RISKSTATE_KILL")]
    KillRiskStateKill,

    #[serde(rename = "KILL_MARGIN_MM_UTIL_CRITICAL")]
    KillMarginMmUtilCritical,

    #[serde(rename = "KILL_RATE_LIMIT_SESSION_TERMINATION")]
    KillRateLimitSessionTermination,

    #[serde(rename = "KILL_DISK_WATERMARK_KILL")]
    KillDiskWatermarkKill,

    #[serde(rename = "KILL_CORTEX_FORCE_KILL")]
    KillCortexForceKill,

    #[serde(rename = "REDUCEONLY_RISKSTATE_MAINTENANCE")]
    ReduceOnlyRiskStateMaintenance,

    #[serde(rename = "REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE")]
    ReduceOnlyEmergencyReduceOnlyActive,

    #[serde(rename = "REDUCEONLY_OPEN_PERMISSION_LATCHED")]
    ReduceOnlyOpenPermissionLatched,

    #[serde(rename = "REDUCEONLY_BUNKER_MODE_ACTIVE")]
    ReduceOnlyBunkerModeActive,

    #[serde(rename = "REDUCEONLY_F1_CERT_INVALID")]
    ReduceOnlyF1CertInvalid,

    #[serde(rename = "REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN")]
    ReduceOnlyEvidenceChainNotGreen,

    #[serde(rename = "REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY")]
    ReduceOnlyCortexForceReduceOnly,

    #[serde(rename = "REDUCEONLY_FEE_MODEL_HARD_STALE")]
    ReduceOnlyFeeModelHardStale,

    #[serde(rename = "REDUCEONLY_RISKSTATE_DEGRADED")]
    ReduceOnlyRiskStateDegraded,

    #[serde(rename = "REDUCEONLY_POLICY_STALE")]
    ReduceOnlyPolicyStale,

    #[serde(rename = "REDUCEONLY_MARGIN_MM_UTIL_HIGH")]
    ReduceOnlyMarginMmUtilHigh,

    #[serde(rename = "REDUCEONLY_INPUT_MISSING_OR_STALE")]
    ReduceOnlyInputMissingOrStale,

    #[serde(rename = "REDUCEONLY_WATCHDOG_UNCONFIRMED")]
    ReduceOnlyWatchdogUnconfirmed,

    #[serde(rename = "REDUCEONLY_DISK_KILL_UNCONFIRMED")]
    ReduceOnlyDiskKillUnconfirmed,

    #[serde(rename = "REDUCEONLY_SESSION_KILL_UNCONFIRMED")]
    ReduceOnlySessionKillUnconfirmed,
}

impl ModeReasonCode {
    pub const ALL: &'static [Self] = &[
        Self::KillWatchdogHeartbeatStale,
        Self::KillRiskStateKill,
        Self::KillMarginMmUtilCritical,
        Self::KillRateLimitSessionTermination,
        Self::KillDiskWatermarkKill,
        Self::KillCortexForceKill,
        Self::ReduceOnlyRiskStateMaintenance,
        Self::ReduceOnlyEmergencyReduceOnlyActive,
        Self::ReduceOnlyOpenPermissionLatched,
        Self::ReduceOnlyBunkerModeActive,
        Self::ReduceOnlyF1CertInvalid,
        Self::ReduceOnlyEvidenceChainNotGreen,
        Self::ReduceOnlyCortexForceReduceOnly,
        Self::ReduceOnlyFeeModelHardStale,
        Self::ReduceOnlyRiskStateDegraded,
        Self::ReduceOnlyPolicyStale,
        Self::ReduceOnlyMarginMmUtilHigh,
        Self::ReduceOnlyInputMissingOrStale,
        Self::ReduceOnlyWatchdogUnconfirmed,
        Self::ReduceOnlyDiskKillUnconfirmed,
        Self::ReduceOnlySessionKillUnconfirmed,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::KillWatchdogHeartbeatStale => "KILL_WATCHDOG_HEARTBEAT_STALE",
            Self::KillRiskStateKill => "KILL_RISKSTATE_KILL",
            Self::KillMarginMmUtilCritical => "KILL_MARGIN_MM_UTIL_CRITICAL",
            Self::KillRateLimitSessionTermination => "KILL_RATE_LIMIT_SESSION_TERMINATION",
            Self::KillDiskWatermarkKill => "KILL_DISK_WATERMARK_KILL",
            Self::KillCortexForceKill => "KILL_CORTEX_FORCE_KILL",
            Self::ReduceOnlyRiskStateMaintenance => "REDUCEONLY_RISKSTATE_MAINTENANCE",
            Self::ReduceOnlyEmergencyReduceOnlyActive => "REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE",
            Self::ReduceOnlyOpenPermissionLatched => "REDUCEONLY_OPEN_PERMISSION_LATCHED",
            Self::ReduceOnlyBunkerModeActive => "REDUCEONLY_BUNKER_MODE_ACTIVE",
            Self::ReduceOnlyF1CertInvalid => "REDUCEONLY_F1_CERT_INVALID",
            Self::ReduceOnlyEvidenceChainNotGreen => "REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN",
            Self::ReduceOnlyCortexForceReduceOnly => "REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY",
            Self::ReduceOnlyFeeModelHardStale => "REDUCEONLY_FEE_MODEL_HARD_STALE",
            Self::ReduceOnlyRiskStateDegraded => "REDUCEONLY_RISKSTATE_DEGRADED",
            Self::ReduceOnlyPolicyStale => "REDUCEONLY_POLICY_STALE",
            Self::ReduceOnlyMarginMmUtilHigh => "REDUCEONLY_MARGIN_MM_UTIL_HIGH",
            Self::ReduceOnlyInputMissingOrStale => "REDUCEONLY_INPUT_MISSING_OR_STALE",
            Self::ReduceOnlyWatchdogUnconfirmed => "REDUCEONLY_WATCHDOG_UNCONFIRMED",
            Self::ReduceOnlyDiskKillUnconfirmed => "REDUCEONLY_DISK_KILL_UNCONFIRMED",
            Self::ReduceOnlySessionKillUnconfirmed => "REDUCEONLY_SESSION_KILL_UNCONFIRMED",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[allow(clippy::enum_variant_names)]
pub enum OpenPermissionReasonCode {
    #[serde(rename = "RESTART_RECONCILE_REQUIRED")]
    RestartReconcileRequired,

    #[serde(rename = "WS_BOOK_GAP_RECONCILE_REQUIRED")]
    WsBookGapReconcileRequired,

    #[serde(rename = "WS_TRADES_GAP_RECONCILE_REQUIRED")]
    WsTradesGapReconcileRequired,

    #[serde(rename = "WS_DATA_STALE_RECONCILE_REQUIRED")]
    WsDataStaleReconcileRequired,

    #[serde(rename = "INVENTORY_MISMATCH_RECONCILE_REQUIRED")]
    InventoryMismatchReconcileRequired,

    #[serde(rename = "SESSION_TERMINATION_RECONCILE_REQUIRED")]
    SessionTerminationReconcileRequired,
}

impl OpenPermissionReasonCode {
    pub const ALL: &'static [Self] = &[
        Self::RestartReconcileRequired,
        Self::WsBookGapReconcileRequired,
        Self::WsTradesGapReconcileRequired,
        Self::WsDataStaleReconcileRequired,
        Self::InventoryMismatchReconcileRequired,
        Self::SessionTerminationReconcileRequired,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::RestartReconcileRequired => "RESTART_RECONCILE_REQUIRED",
            Self::WsBookGapReconcileRequired => "WS_BOOK_GAP_RECONCILE_REQUIRED",
            Self::WsTradesGapReconcileRequired => "WS_TRADES_GAP_RECONCILE_REQUIRED",
            Self::WsDataStaleReconcileRequired => "WS_DATA_STALE_RECONCILE_REQUIRED",
            Self::InventoryMismatchReconcileRequired => "INVENTORY_MISMATCH_RECONCILE_REQUIRED",
            Self::SessionTerminationReconcileRequired => "SESSION_TERMINATION_RECONCILE_REQUIRED",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[allow(clippy::enum_variant_names)]
pub enum OwnerStateCode {
    #[serde(rename = "STATE_STARTUP_RECONCILING")]
    StateStartupReconciling,

    #[serde(rename = "STATE_IDLE_HEALTHY")]
    StateIdleHealthy,

    #[serde(rename = "STATE_PAPER_MODE")]
    StatePaperMode,

    #[serde(rename = "STATE_MICRO_LIVE")]
    StateMicroLive,

    #[serde(rename = "STATE_UNHEALTHY_STATUS_SCHEMA")]
    StateUnhealthyStatusSchema,
}

impl OwnerStateCode {
    pub const ALL: &'static [Self] = &[
        Self::StateStartupReconciling,
        Self::StateIdleHealthy,
        Self::StatePaperMode,
        Self::StateMicroLive,
        Self::StateUnhealthyStatusSchema,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::StateStartupReconciling => "STATE_STARTUP_RECONCILING",
            Self::StateIdleHealthy => "STATE_IDLE_HEALTHY",
            Self::StatePaperMode => "STATE_PAPER_MODE",
            Self::StateMicroLive => "STATE_MICRO_LIVE",
            Self::StateUnhealthyStatusSchema => "STATE_UNHEALTHY_STATUS_SCHEMA",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnblockMeta {
    pub unblock_type: &'static str,
    pub condition: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ModeReasonMeta {
    pub display: &'static str,
    pub latched: bool,
    pub unblock: UnblockMeta,
    pub tier: TradingMode,
}

impl ModeReasonCode {
    pub const fn meta(self) -> ModeReasonMeta {
        match self {
            Self::KillWatchdogHeartbeatStale => ModeReasonMeta {
                display: "Hot loop appears dead (watchdog stale).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Incident record + system restart + heartbeat confirmed",
                },
                tier: TradingMode::Kill,
            },
            Self::KillRiskStateKill => ModeReasonMeta {
                display: "RiskState is Kill (explicit emergency condition).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Incident record + explicit operator reset",
                },
                tier: TradingMode::Kill,
            },
            Self::KillMarginMmUtilCritical => ModeReasonMeta {
                display: "Margin utilization is critical (near liquidation).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "mm_util < 0.90 for >= 300s",
                },
                tier: TradingMode::Kill,
            },
            Self::KillRateLimitSessionTermination => ModeReasonMeta {
                display: "Exchange session terminated (10028 / rate-limit kill).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Re-auth + full reconciliation + incident record",
                },
                tier: TradingMode::Kill,
            },
            Self::KillDiskWatermarkKill => ModeReasonMeta {
                display: "Disk watermark kill (integrity risk).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Disk cleanup + verification + restart",
                },
                tier: TradingMode::Kill,
            },
            Self::KillCortexForceKill => ModeReasonMeta {
                display: "Market microstructure collapse or contract violation (Cortex Kill).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Fix deployed + incident record + explicit approval",
                },
                tier: TradingMode::Kill,
            },
            Self::ReduceOnlyRiskStateMaintenance => ModeReasonMeta {
                display: "Exchange maintenance window (no new opens).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Exchange maintenance ends + connectivity confirmed",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyEmergencyReduceOnlyActive => ModeReasonMeta {
                display: "Emergency ReduceOnly latch is active (cooldown).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Cooldown expires (configurable, default 300s)",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyOpenPermissionLatched => ModeReasonMeta {
                display: "Open-permission latch is set (reconcile required).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Reconciliation succeeds + latch clears",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyBunkerModeActive => ModeReasonMeta {
                display: "Connectivity/jitter risk (Bunker mode).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Connectivity stable for >= 60s",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyF1CertInvalid => ModeReasonMeta {
                display: "F1 certification missing/stale/invalid (fail-closed).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Re-certify + deploy certified build",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyEvidenceChainNotGreen => ModeReasonMeta {
                display: "Evidence chain not GREEN (GOP/FULL profiles only).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Evidence chain returns to GREEN",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyCortexForceReduceOnly => ModeReasonMeta {
                display: "Market stress detected (Cortex ReduceOnly).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Cortex stress signal clears",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyFeeModelHardStale => ModeReasonMeta {
                display: "Fee model hard-stale (cannot trust edge calculations).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Fee model refreshed within staleness threshold",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyRiskStateDegraded => ModeReasonMeta {
                display: "RiskState is Degraded (system protecting capital).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "RiskState returns to Healthy",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyPolicyStale => ModeReasonMeta {
                display: "Policy is stale (no trading on old policy).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Policy refreshed within staleness threshold",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyMarginMmUtilHigh => ModeReasonMeta {
                display: "Margin utilization high (reduce only).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "mm_util < 0.80 for >= 60s",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyInputMissingOrStale => ModeReasonMeta {
                display: "Critical input missing/stale (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "All required inputs fresh",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyWatchdogUnconfirmed => ModeReasonMeta {
                display: "One watchdog corroboration signal missing (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "All watchdog signals confirmed",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlyDiskKillUnconfirmed => ModeReasonMeta {
                display: "Disk kill predicate unconfirmed (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Disk predicate confirmed safe",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceOnlySessionKillUnconfirmed => ModeReasonMeta {
                display: "Session kill predicate unconfirmed (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Session predicate confirmed safe",
                },
                tier: TradingMode::ReduceOnly,
            },
        }
    }
}
