//! Generated status and reason-code surface.
//!
//! Owns: generated enums for trading mode, risk state, mode/open-permission/
//! owner-state reason codes, deployment environment, F1 cert state, plus
//! their metadata structs.
//!
//! **Public:** all symbols from `status_codes_generated.rs` via `pub use generated::*`.
//!
//! **Private:** `generated` (inline module wrapping the codegen include).
//!
//! **Tests:** facade completeness in inline `facade_completeness_contract_tests`.
//! Source regenerated by `tools/generate_reason_codes.py`.

mod generated {
    include!("status_codes_generated.rs");
}

pub use generated::*;

#[cfg(test)]
mod facade_completeness_contract_tests {
    //! Compile-time proof that intended facade symbols are reachable via
    //! `crate::status_codes::{...}`.

    #[allow(unused_imports)]
    use crate::status_codes::{
        DeploymentEnvironment, F1CertState, ModeReasonCode, ModeReasonMeta,
        OpenPermissionReasonCode, OpenPermissionReasonMeta, OwnerStateCode, OwnerStateMeta,
        RiskState, TradingMode, UnblockMeta,
    };

    #[test]
    fn facade_symbols_reachable_via_status_codes_facade() {
        assert_eq!(TradingMode::Active.as_str(), "Active");
        assert_eq!(RiskState::Healthy.as_str(), "Healthy");
        assert_eq!(
            ModeReasonCode::KillWatchdogHeartbeatStale.meta().tier,
            TradingMode::Kill
        );
    }
}
