// @generated by tools/generate_reason_codes.py
// source: specs/status/status_reason_registries_manifest.json
// DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum TradingMode {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "ReduceOnly")]
    ReduceOnly,
    #[serde(rename = "Kill")]
    Kill,
}

impl TradingMode {
    pub const ALL: &'static [Self] = &[
        Self::Active,
        Self::ReduceOnly,
        Self::Kill,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Active => "Active",
            Self::ReduceOnly => "ReduceOnly",
            Self::Kill => "Kill",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DeploymentEnvironment {
    #[serde(rename = "DEV")]
    Dev,
    #[serde(rename = "STAGING")]
    Staging,
    #[serde(rename = "PAPER")]
    Paper,
    #[serde(rename = "LIVE")]
    Live,
}

impl DeploymentEnvironment {
    pub const ALL: &'static [Self] = &[
        Self::Dev,
        Self::Staging,
        Self::Paper,
        Self::Live,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Dev => "DEV",
            Self::Staging => "STAGING",
            Self::Paper => "PAPER",
            Self::Live => "LIVE",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RiskState {
    #[serde(rename = "Healthy")]
    Healthy,
    #[serde(rename = "Degraded")]
    Degraded,
    #[serde(rename = "Maintenance")]
    Maintenance,
}

impl RiskState {
    pub const ALL: &'static [Self] = &[
        Self::Healthy,
        Self::Degraded,
        Self::Maintenance,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Healthy => "Healthy",
            Self::Degraded => "Degraded",
            Self::Maintenance => "Maintenance",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum F1CertState {
    #[serde(rename = "PASS")]
    Pass,
    #[serde(rename = "FAIL")]
    Fail,
    #[serde(rename = "STALE")]
    Stale,
    #[serde(rename = "MISSING")]
    Missing,
    #[serde(rename = "INVALID")]
    Invalid,
}

impl F1CertState {
    pub const ALL: &'static [Self] = &[
        Self::Pass,
        Self::Fail,
        Self::Stale,
        Self::Missing,
        Self::Invalid,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pass => "PASS",
            Self::Fail => "FAIL",
            Self::Stale => "STALE",
            Self::Missing => "MISSING",
            Self::Invalid => "INVALID",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ModeReasonCode {
    #[serde(rename = "KILL_WATCHDOG_HEARTBEAT_STALE")]
    KillWatchdogHeartbeatStale,
    #[serde(rename = "KILL_RISKSTATE_KILL")]
    KillRiskstateKill,
    #[serde(rename = "KILL_MARGIN_MM_UTIL_CRITICAL")]
    KillMarginMmUtilCritical,
    #[serde(rename = "KILL_RATE_LIMIT_SESSION_TERMINATION")]
    KillRateLimitSessionTermination,
    #[serde(rename = "KILL_DISK_WATERMARK_KILL")]
    KillDiskWatermarkKill,
    #[serde(rename = "KILL_CORTEX_FORCE_KILL")]
    KillCortexForceKill,
    #[serde(rename = "REDUCEONLY_RISKSTATE_MAINTENANCE")]
    ReduceonlyRiskstateMaintenance,
    #[serde(rename = "REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE")]
    ReduceonlyEmergencyReduceonlyActive,
    #[serde(rename = "REDUCEONLY_OPEN_PERMISSION_LATCHED")]
    ReduceonlyOpenPermissionLatched,
    #[serde(rename = "REDUCEONLY_OPEN_PERMISSION_LATCHED_V2")]
    ReduceonlyOpenPermissionLatchedV2,
    #[serde(rename = "REDUCEONLY_BUNKER_MODE_ACTIVE")]
    ReduceonlyBunkerModeActive,
    #[serde(rename = "REDUCEONLY_F1_CERT_INVALID")]
    ReduceonlyF1CertInvalid,
    #[serde(rename = "REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN")]
    ReduceonlyEvidenceChainNotGreen,
    #[serde(rename = "REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY")]
    ReduceonlyCortexForceReduceOnly,
    #[serde(rename = "REDUCEONLY_FEE_MODEL_HARD_STALE")]
    ReduceonlyFeeModelHardStale,
    #[serde(rename = "REDUCEONLY_RISKSTATE_DEGRADED")]
    ReduceonlyRiskstateDegraded,
    #[serde(rename = "REDUCEONLY_POLICY_STALE")]
    ReduceonlyPolicyStale,
    #[serde(rename = "REDUCEONLY_MARGIN_MM_UTIL_HIGH")]
    ReduceonlyMarginMmUtilHigh,
    #[serde(rename = "REDUCEONLY_INPUT_MISSING_OR_STALE")]
    ReduceonlyInputMissingOrStale,
    #[serde(rename = "REDUCEONLY_WATCHDOG_UNCONFIRMED")]
    ReduceonlyWatchdogUnconfirmed,
    #[serde(rename = "REDUCEONLY_DISK_KILL_UNCONFIRMED")]
    ReduceonlyDiskKillUnconfirmed,
    #[serde(rename = "REDUCEONLY_SESSION_KILL_UNCONFIRMED")]
    ReduceonlySessionKillUnconfirmed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnblockMeta {
    pub unblock_type: &'static str,
    pub condition: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ModeReasonMeta {
    pub display: &'static str,
    pub latched: bool,
    pub unblock: UnblockMeta,
    pub tier: TradingMode,
}

impl ModeReasonCode {
    pub const ALL: &'static [Self] = &[
        Self::KillWatchdogHeartbeatStale,
        Self::KillRiskstateKill,
        Self::KillMarginMmUtilCritical,
        Self::KillRateLimitSessionTermination,
        Self::KillDiskWatermarkKill,
        Self::KillCortexForceKill,
        Self::ReduceonlyRiskstateMaintenance,
        Self::ReduceonlyEmergencyReduceonlyActive,
        Self::ReduceonlyOpenPermissionLatched,
        Self::ReduceonlyOpenPermissionLatchedV2,
        Self::ReduceonlyBunkerModeActive,
        Self::ReduceonlyF1CertInvalid,
        Self::ReduceonlyEvidenceChainNotGreen,
        Self::ReduceonlyCortexForceReduceOnly,
        Self::ReduceonlyFeeModelHardStale,
        Self::ReduceonlyRiskstateDegraded,
        Self::ReduceonlyPolicyStale,
        Self::ReduceonlyMarginMmUtilHigh,
        Self::ReduceonlyInputMissingOrStale,
        Self::ReduceonlyWatchdogUnconfirmed,
        Self::ReduceonlyDiskKillUnconfirmed,
        Self::ReduceonlySessionKillUnconfirmed,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::KillWatchdogHeartbeatStale => "KILL_WATCHDOG_HEARTBEAT_STALE",
            Self::KillRiskstateKill => "KILL_RISKSTATE_KILL",
            Self::KillMarginMmUtilCritical => "KILL_MARGIN_MM_UTIL_CRITICAL",
            Self::KillRateLimitSessionTermination => "KILL_RATE_LIMIT_SESSION_TERMINATION",
            Self::KillDiskWatermarkKill => "KILL_DISK_WATERMARK_KILL",
            Self::KillCortexForceKill => "KILL_CORTEX_FORCE_KILL",
            Self::ReduceonlyRiskstateMaintenance => "REDUCEONLY_RISKSTATE_MAINTENANCE",
            Self::ReduceonlyEmergencyReduceonlyActive => "REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE",
            Self::ReduceonlyOpenPermissionLatched => "REDUCEONLY_OPEN_PERMISSION_LATCHED",
            Self::ReduceonlyOpenPermissionLatchedV2 => "REDUCEONLY_OPEN_PERMISSION_LATCHED_V2",
            Self::ReduceonlyBunkerModeActive => "REDUCEONLY_BUNKER_MODE_ACTIVE",
            Self::ReduceonlyF1CertInvalid => "REDUCEONLY_F1_CERT_INVALID",
            Self::ReduceonlyEvidenceChainNotGreen => "REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN",
            Self::ReduceonlyCortexForceReduceOnly => "REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY",
            Self::ReduceonlyFeeModelHardStale => "REDUCEONLY_FEE_MODEL_HARD_STALE",
            Self::ReduceonlyRiskstateDegraded => "REDUCEONLY_RISKSTATE_DEGRADED",
            Self::ReduceonlyPolicyStale => "REDUCEONLY_POLICY_STALE",
            Self::ReduceonlyMarginMmUtilHigh => "REDUCEONLY_MARGIN_MM_UTIL_HIGH",
            Self::ReduceonlyInputMissingOrStale => "REDUCEONLY_INPUT_MISSING_OR_STALE",
            Self::ReduceonlyWatchdogUnconfirmed => "REDUCEONLY_WATCHDOG_UNCONFIRMED",
            Self::ReduceonlyDiskKillUnconfirmed => "REDUCEONLY_DISK_KILL_UNCONFIRMED",
            Self::ReduceonlySessionKillUnconfirmed => "REDUCEONLY_SESSION_KILL_UNCONFIRMED",
        }
    }

    pub const fn meta(self) -> ModeReasonMeta {
        match self {
            Self::KillWatchdogHeartbeatStale => ModeReasonMeta {
                display: "Hot loop appears dead (watchdog stale).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Incident record + system restart + heartbeat confirmed",
                },
                tier: TradingMode::Kill,
            },
            Self::KillRiskstateKill => ModeReasonMeta {
                display: "RiskState is Kill (explicit emergency condition).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Incident record + explicit operator reset",
                },
                tier: TradingMode::Kill,
            },
            Self::KillMarginMmUtilCritical => ModeReasonMeta {
                display: "Margin utilization is critical (near liquidation).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "mm_util < 0.90 for >= 300s",
                },
                tier: TradingMode::Kill,
            },
            Self::KillRateLimitSessionTermination => ModeReasonMeta {
                display: "Exchange session terminated (10028 / rate-limit kill).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Re-auth + full reconciliation + incident record",
                },
                tier: TradingMode::Kill,
            },
            Self::KillDiskWatermarkKill => ModeReasonMeta {
                display: "Disk watermark kill (integrity risk).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Disk cleanup + verification + restart",
                },
                tier: TradingMode::Kill,
            },
            Self::KillCortexForceKill => ModeReasonMeta {
                display: "Market microstructure collapse or contract violation (Cortex Kill).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Fix deployed + incident record + explicit approval",
                },
                tier: TradingMode::Kill,
            },
            Self::ReduceonlyRiskstateMaintenance => ModeReasonMeta {
                display: "Exchange maintenance window (no new opens).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Exchange maintenance ends + connectivity confirmed",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyEmergencyReduceonlyActive => ModeReasonMeta {
                display: "Emergency ReduceOnly latch is active (cooldown).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Cooldown expires (configurable, default 300s)",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyOpenPermissionLatched => ModeReasonMeta {
                display: "Open-permission latch is set (reconcile required).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Reconciliation succeeds + latch clears",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyOpenPermissionLatchedV2 => ModeReasonMeta {
                display: "Open-permission latch is set (schema v2 semantics).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Reconciliation succeeds + latch clears",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyBunkerModeActive => ModeReasonMeta {
                display: "Connectivity/jitter risk (Bunker mode).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Connectivity stable for >= 60s",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyF1CertInvalid => ModeReasonMeta {
                display: "F1 certification missing/stale/invalid (fail-closed).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Re-certify + deploy certified build",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyEvidenceChainNotGreen => ModeReasonMeta {
                display: "Evidence chain not GREEN (GOP/FULL profiles only).",
                latched: true,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Evidence chain returns to GREEN",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyCortexForceReduceOnly => ModeReasonMeta {
                display: "Market stress detected (Cortex ReduceOnly).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Cortex stress signal clears",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyFeeModelHardStale => ModeReasonMeta {
                display: "Fee model hard-stale (cannot trust edge calculations).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Fee model refreshed within staleness threshold",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyRiskstateDegraded => ModeReasonMeta {
                display: "RiskState is Degraded (system protecting capital).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "RiskState returns to Healthy",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyPolicyStale => ModeReasonMeta {
                display: "Policy is stale (no trading on old policy).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Policy refreshed within staleness threshold",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyMarginMmUtilHigh => ModeReasonMeta {
                display: "Margin utilization high (reduce only).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "mm_util < 0.80 for >= 60s",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyInputMissingOrStale => ModeReasonMeta {
                display: "Critical input missing/stale (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "All required inputs fresh",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyWatchdogUnconfirmed => ModeReasonMeta {
                display: "One watchdog corroboration signal missing (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "All watchdog signals confirmed",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlyDiskKillUnconfirmed => ModeReasonMeta {
                display: "Disk kill predicate unconfirmed (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Disk predicate confirmed safe",
                },
                tier: TradingMode::ReduceOnly,
            },
            Self::ReduceonlySessionKillUnconfirmed => ModeReasonMeta {
                display: "Session kill predicate unconfirmed (fail-closed).",
                latched: false,
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Session predicate confirmed safe",
                },
                tier: TradingMode::ReduceOnly,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum OpenPermissionReasonCode {
    #[serde(rename = "RESTART_RECONCILE_REQUIRED")]
    RestartReconcileRequired,
    #[serde(rename = "WS_BOOK_GAP_RECONCILE_REQUIRED")]
    WsBookGapReconcileRequired,
    #[serde(rename = "WS_TRADES_GAP_RECONCILE_REQUIRED")]
    WsTradesGapReconcileRequired,
    #[serde(rename = "WS_DATA_STALE_RECONCILE_REQUIRED")]
    WsDataStaleReconcileRequired,
    #[serde(rename = "INVENTORY_MISMATCH_RECONCILE_REQUIRED")]
    InventoryMismatchReconcileRequired,
    #[serde(rename = "SESSION_TERMINATION_RECONCILE_REQUIRED")]
    SessionTerminationReconcileRequired,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenPermissionReasonMeta {
    pub display: &'static str,
    pub unblock: UnblockMeta,
}

impl OpenPermissionReasonCode {
    pub const ALL: &'static [Self] = &[
        Self::RestartReconcileRequired,
        Self::WsBookGapReconcileRequired,
        Self::WsTradesGapReconcileRequired,
        Self::WsDataStaleReconcileRequired,
        Self::InventoryMismatchReconcileRequired,
        Self::SessionTerminationReconcileRequired,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::RestartReconcileRequired => "RESTART_RECONCILE_REQUIRED",
            Self::WsBookGapReconcileRequired => "WS_BOOK_GAP_RECONCILE_REQUIRED",
            Self::WsTradesGapReconcileRequired => "WS_TRADES_GAP_RECONCILE_REQUIRED",
            Self::WsDataStaleReconcileRequired => "WS_DATA_STALE_RECONCILE_REQUIRED",
            Self::InventoryMismatchReconcileRequired => "INVENTORY_MISMATCH_RECONCILE_REQUIRED",
            Self::SessionTerminationReconcileRequired => "SESSION_TERMINATION_RECONCILE_REQUIRED",
        }
    }

    pub const fn meta(self) -> OpenPermissionReasonMeta {
        match self {
            Self::RestartReconcileRequired => OpenPermissionReasonMeta {
                display: "Restarted \u{2014} must reconcile before opening risk.",
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Reconciliation completes successfully",
                },
            },
            Self::WsBookGapReconcileRequired => OpenPermissionReasonMeta {
                display: "Order book feed gap \u{2014} must reconcile.",
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Book snapshot refreshed + no gaps for >= 10s",
                },
            },
            Self::WsTradesGapReconcileRequired => OpenPermissionReasonMeta {
                display: "Trades feed gap \u{2014} must reconcile.",
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Trades stream continuous + reconciled",
                },
            },
            Self::WsDataStaleReconcileRequired => OpenPermissionReasonMeta {
                display: "Market-data silence \u{2014} must reconcile.",
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "ws_event_lag_ms <= 500 for >= 60s + reconciliation",
                },
            },
            Self::InventoryMismatchReconcileRequired => OpenPermissionReasonMeta {
                display: "Position mismatch \u{2014} must reconcile.",
                unblock: UnblockMeta {
                    unblock_type: "AUTO",
                    condition: "Local inventory matches venue truth",
                },
            },
            Self::SessionTerminationReconcileRequired => OpenPermissionReasonMeta {
                display: "Session terminated \u{2014} must reconcile.",
                unblock: UnblockMeta {
                    unblock_type: "MANUAL",
                    condition: "Re-authenticate + full reconciliation",
                },
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum OwnerStateCode {
    #[serde(rename = "STATE_STARTUP_RECONCILING")]
    StateStartupReconciling,
    #[serde(rename = "STATE_IDLE_HEALTHY")]
    StateIdleHealthy,
    #[serde(rename = "STATE_PAPER_MODE")]
    StatePaperMode,
    #[serde(rename = "STATE_MICRO_LIVE")]
    StateMicroLive,
    #[serde(rename = "STATE_UNHEALTHY_STATUS_SCHEMA")]
    StateUnhealthyStatusSchema,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OwnerStateMeta {
    pub display: &'static str,
}

impl OwnerStateCode {
    pub const ALL: &'static [Self] = &[
        Self::StateStartupReconciling,
        Self::StateIdleHealthy,
        Self::StatePaperMode,
        Self::StateMicroLive,
        Self::StateUnhealthyStatusSchema,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::StateStartupReconciling => "STATE_STARTUP_RECONCILING",
            Self::StateIdleHealthy => "STATE_IDLE_HEALTHY",
            Self::StatePaperMode => "STATE_PAPER_MODE",
            Self::StateMicroLive => "STATE_MICRO_LIVE",
            Self::StateUnhealthyStatusSchema => "STATE_UNHEALTHY_STATUS_SCHEMA",
        }
    }

    pub const fn meta(self) -> OwnerStateMeta {
        match self {
            Self::StateStartupReconciling => OwnerStateMeta {
                display: "Starting up and reconciling venue truth.",
            },
            Self::StateIdleHealthy => OwnerStateMeta {
                display: "Healthy and idle (no signals or no orders to send).",
            },
            Self::StatePaperMode => OwnerStateMeta {
                display: "Paper trading (no real orders).",
            },
            Self::StateMicroLive => OwnerStateMeta {
                display: "Live trading with micro-caps enforced.",
            },
            Self::StateUnhealthyStatusSchema => OwnerStateMeta {
                display: "Status schema invalid (fail-closed). Contact engineering.",
            },
        }
    }
}
