[package]
name = "soldier_core"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
xxhash-rust = { version = "0.8", features = ["xxh64"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
proptest = "1"
serde_json = "1"
tracing-test = "0.2"
soldier_core = { path = ".", features = ["test-helpers"] }

[features]
test-helpers = []
