#!/usr/bin/env bash
set -euo pipefail

# Generate proposed allowlist patch from PRD verify[] commands
# READ-ONLY: prints patch to stdout, does NOT modify any files
# Usage: ./plans/story_verify_allowlist_suggest.sh [prd.json] > allowlist.patch

ALLOWLIST="${RPH_STORY_VERIFY_ALLOWLIST_FILE:-plans/story_verify_allowlist.txt}"
ARG_PRD_FILE="${1:-}"
PRD_FILE="${ARG_PRD_FILE:-${PRD_FILE:-plans/prd.json}}"

if ! command -v jq >/dev/null 2>&1; then
  echo "# ERROR: jq required" >&2
  exit 2
fi

if [[ ! -f "$ALLOWLIST" ]]; then
  echo "# ERROR: Allowlist not found: $ALLOWLIST" >&2
  exit 2
fi

if [[ ! -f "$PRD_FILE" ]]; then
  echo "# ERROR: PRD file not found: $PRD_FILE" >&2
  exit 2
fi

# Extract all verify commands from PRD (exclude ./plans/verify.sh)
prd_commands=$(jq -r '.items[].verify[]' "$PRD_FILE" 2>/dev/null | \
  grep -Fxv "./plans/verify.sh" | sort -u || true)

# Load allowlist (strip empty lines and comments)
allowlist_commands=$(grep -v '^[[:space:]]*#' "$ALLOWLIST" 2>/dev/null | grep -v '^[[:space:]]*$' | sort -u || true)

# Find missing (in PRD but not in allowlist)
missing_arr=()
if [[ -n "$prd_commands" ]]; then
  while IFS= read -r cmd; do
    [[ -z "$cmd" ]] && continue
    if ! echo "$allowlist_commands" | grep -Fxq "$cmd"; then
      missing_arr+=("$cmd")
    fi
  done <<< "$prd_commands"
fi

# Find orphaned (in allowlist but not in PRD)
orphaned_arr=()
if [[ -n "$allowlist_commands" ]]; then
  while IFS= read -r cmd; do
    [[ -z "$cmd" ]] && continue
    if [[ -z "$prd_commands" ]] || ! echo "$prd_commands" | grep -Fxq "$cmd"; then
      orphaned_arr+=("$cmd")
    fi
  done <<< "$allowlist_commands"
fi

# Generate patch
echo "# Proposed allowlist changes (generated by story_verify_allowlist_suggest.sh)"
echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# PRD: $PRD_FILE"
echo "#"

if [[ ${#missing_arr[@]} -gt 0 ]]; then
  echo "# ADD these entries to $ALLOWLIST:"
  printf '%s\n' "${missing_arr[@]}"
  echo "#"
fi

if [[ ${#orphaned_arr[@]} -gt 0 ]]; then
  echo "# CONSIDER REMOVING these orphaned entries from $ALLOWLIST:"
  printf '# %s\n' "${orphaned_arr[@]}"
  echo "#"
fi

if [[ ${#missing_arr[@]} -eq 0 && ${#orphaned_arr[@]} -eq 0 ]]; then
  echo "# No changes needed - allowlist is in sync with PRD"
fi

echo "# To apply additions: ./plans/story_verify_allowlist_suggest.sh | grep -v '^#' >> $ALLOWLIST"
