# @generated by tools/generate_reason_codes.py
# source: specs/status/status_reason_registries_manifest.json
# DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Final

class TradingMode(str, Enum):
    ACTIVE = "Active"
    REDUCE_ONLY = "ReduceOnly"
    KILL = "Kill"

class DeploymentEnvironment(str, Enum):
    DEV = "DEV"
    STAGING = "STAGING"
    PAPER = "PAPER"
    LIVE = "LIVE"

class RiskState(str, Enum):
    HEALTHY = "Healthy"
    DEGRADED = "Degraded"
    MAINTENANCE = "Maintenance"

class F1CertState(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    STALE = "STALE"
    MISSING = "MISSING"
    INVALID = "INVALID"

class ModeReasonCode(str, Enum):
    KILL_WATCHDOG_HEARTBEAT_STALE = "KILL_WATCHDOG_HEARTBEAT_STALE"
    KILL_RISKSTATE_KILL = "KILL_RISKSTATE_KILL"
    KILL_MARGIN_MM_UTIL_CRITICAL = "KILL_MARGIN_MM_UTIL_CRITICAL"
    KILL_RATE_LIMIT_SESSION_TERMINATION = "KILL_RATE_LIMIT_SESSION_TERMINATION"
    KILL_DISK_WATERMARK_KILL = "KILL_DISK_WATERMARK_KILL"
    KILL_CORTEX_FORCE_KILL = "KILL_CORTEX_FORCE_KILL"
    REDUCEONLY_RISKSTATE_MAINTENANCE = "REDUCEONLY_RISKSTATE_MAINTENANCE"
    REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE = "REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE"
    REDUCEONLY_OPEN_PERMISSION_LATCHED = "REDUCEONLY_OPEN_PERMISSION_LATCHED"
    REDUCEONLY_BUNKER_MODE_ACTIVE = "REDUCEONLY_BUNKER_MODE_ACTIVE"
    REDUCEONLY_F1_CERT_INVALID = "REDUCEONLY_F1_CERT_INVALID"
    REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN = "REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN"
    REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY = "REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY"
    REDUCEONLY_FEE_MODEL_HARD_STALE = "REDUCEONLY_FEE_MODEL_HARD_STALE"
    REDUCEONLY_RISKSTATE_DEGRADED = "REDUCEONLY_RISKSTATE_DEGRADED"
    REDUCEONLY_POLICY_STALE = "REDUCEONLY_POLICY_STALE"
    REDUCEONLY_MARGIN_MM_UTIL_HIGH = "REDUCEONLY_MARGIN_MM_UTIL_HIGH"
    REDUCEONLY_INPUT_MISSING_OR_STALE = "REDUCEONLY_INPUT_MISSING_OR_STALE"
    REDUCEONLY_WATCHDOG_UNCONFIRMED = "REDUCEONLY_WATCHDOG_UNCONFIRMED"
    REDUCEONLY_DISK_KILL_UNCONFIRMED = "REDUCEONLY_DISK_KILL_UNCONFIRMED"
    REDUCEONLY_SESSION_KILL_UNCONFIRMED = "REDUCEONLY_SESSION_KILL_UNCONFIRMED"

class OpenPermissionReasonCode(str, Enum):
    RESTART_RECONCILE_REQUIRED = "RESTART_RECONCILE_REQUIRED"
    WS_BOOK_GAP_RECONCILE_REQUIRED = "WS_BOOK_GAP_RECONCILE_REQUIRED"
    WS_TRADES_GAP_RECONCILE_REQUIRED = "WS_TRADES_GAP_RECONCILE_REQUIRED"
    WS_DATA_STALE_RECONCILE_REQUIRED = "WS_DATA_STALE_RECONCILE_REQUIRED"
    INVENTORY_MISMATCH_RECONCILE_REQUIRED = "INVENTORY_MISMATCH_RECONCILE_REQUIRED"
    SESSION_TERMINATION_RECONCILE_REQUIRED = "SESSION_TERMINATION_RECONCILE_REQUIRED"

class OwnerStateCode(str, Enum):
    STATE_STARTUP_RECONCILING = "STATE_STARTUP_RECONCILING"
    STATE_IDLE_HEALTHY = "STATE_IDLE_HEALTHY"
    STATE_PAPER_MODE = "STATE_PAPER_MODE"
    STATE_MICRO_LIVE = "STATE_MICRO_LIVE"
    STATE_UNHEALTHY_STATUS_SCHEMA = "STATE_UNHEALTHY_STATUS_SCHEMA"

class RejectReasonCode(str, Enum):
    TOO_SMALL_AFTER_QUANTIZATION = "TooSmallAfterQuantization"
    INSTRUMENT_METADATA_MISSING = "InstrumentMetadataMissing"
    CHURN_BREAKER_ACTIVE = "ChurnBreakerActive"
    LIQUIDITY_GATE_NO_L2 = "LiquidityGateNoL2"
    EMERGENCY_CLOSE_NO_PRICE = "EmergencyCloseNoPrice"
    EXPECTED_SLIPPAGE_TOO_HIGH = "ExpectedSlippageTooHigh"
    NET_EDGE_TOO_LOW = "NetEdgeTooLow"
    NET_EDGE_INPUT_MISSING = "NetEdgeInputMissing"
    PRICER_INPUT_MISSING = "PricerInputMissing"
    PRICER_INPUT_INVALID = "PricerInputInvalid"
    GATE_CASCADE_SKIP = "GateCascadeSkip"
    INSUFFICIENT_DEPTH_WITHIN_BUDGET = "InsufficientDepthWithinBudget"
    FEE_CACHE_STALE = "FeeCacheStale"
    RECORDED_BEFORE_DISPATCH_FAILED = "RecordedBeforeDispatchFailed"
    ASSEMBLY_FAILED = "AssemblyFailed"
    INVENTORY_SKEW = "InventorySkew"
    INVENTORY_SKEW_DELTA_LIMIT_MISSING = "InventorySkewDeltaLimitMissing"
    PENDING_EXPOSURE_BUDGET_EXCEEDED = "PendingExposureBudgetExceeded"
    GLOBAL_EXPOSURE_BUDGET_EXCEEDED = "GlobalExposureBudgetExceeded"
    CONTRACTS_AMOUNT_MISMATCH = "ContractsAmountMismatch"
    MARGIN_HEADROOM_REJECT_OPENS = "MarginHeadroomRejectOpens"
    ORDER_TYPE_MARKET_FORBIDDEN = "OrderTypeMarketForbidden"
    ORDER_TYPE_STOP_FORBIDDEN = "OrderTypeStopForbidden"
    LINKED_ORDER_TYPE_FORBIDDEN = "LinkedOrderTypeForbidden"
    POST_ONLY_WOULD_CROSS = "PostOnlyWouldCross"
    RISK_INCREASING_CANCEL_REPLACE_FORBIDDEN = "RiskIncreasingCancelReplaceForbidden"
    RATE_LIMIT_BROWNOUT = "RateLimitBrownout"
    INSTRUMENT_EXPIRED_OR_DELISTED = "InstrumentExpiredOrDelisted"
    FEEDBACK_LOOP_GUARD_ACTIVE = "FeedbackLoopGuardActive"
    LABEL_TOO_LONG = "LabelTooLong"

@dataclass(frozen=True)
class UnblockMeta:
    unblock_type: str
    condition: str


@dataclass(frozen=True)
class ModeReasonMeta:
    display: str
    latched: bool
    unblock: UnblockMeta
    tier: TradingMode


MODE_REASON_META: Final[dict[ModeReasonCode, ModeReasonMeta]] = {
    ModeReasonCode.KILL_WATCHDOG_HEARTBEAT_STALE: ModeReasonMeta(
        display="Hot loop appears dead (watchdog stale).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Incident record + system restart + heartbeat confirmed",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.KILL_RISKSTATE_KILL: ModeReasonMeta(
        display="RiskState is Kill (explicit emergency condition).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Incident record + explicit operator reset",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.KILL_MARGIN_MM_UTIL_CRITICAL: ModeReasonMeta(
        display="Margin utilization is critical (near liquidation).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="mm_util < 0.90 for >= 300s",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.KILL_RATE_LIMIT_SESSION_TERMINATION: ModeReasonMeta(
        display="Exchange session terminated (10028 / rate-limit kill).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Re-auth + full reconciliation + incident record",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.KILL_DISK_WATERMARK_KILL: ModeReasonMeta(
        display="Disk watermark kill (integrity risk).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Disk cleanup + verification + restart",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.KILL_CORTEX_FORCE_KILL: ModeReasonMeta(
        display="Market microstructure collapse or contract violation (Cortex Kill).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Fix deployed + incident record + explicit approval",
        ),
        tier=TradingMode.KILL,
    ),
    ModeReasonCode.REDUCEONLY_RISKSTATE_MAINTENANCE: ModeReasonMeta(
        display="Exchange maintenance window (no new opens).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Exchange maintenance ends + connectivity confirmed",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_EMERGENCY_REDUCEONLY_ACTIVE: ModeReasonMeta(
        display="Emergency ReduceOnly latch is active (cooldown).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Cooldown expires (configurable, default 300s)",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_OPEN_PERMISSION_LATCHED: ModeReasonMeta(
        display="Open-permission latch is set (reconcile required).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Reconciliation succeeds + latch clears",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_BUNKER_MODE_ACTIVE: ModeReasonMeta(
        display="Connectivity/jitter risk (Bunker mode).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Connectivity stable for >= 60s",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_F1_CERT_INVALID: ModeReasonMeta(
        display="F1 certification missing/stale/invalid (fail-closed).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="MANUAL",
            condition="Re-certify + deploy certified build",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_EVIDENCE_CHAIN_NOT_GREEN: ModeReasonMeta(
        display="Evidence chain not GREEN (GOP/FULL profiles only).",
        latched=True,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Evidence chain returns to GREEN",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_CORTEX_FORCE_REDUCE_ONLY: ModeReasonMeta(
        display="Market stress detected (Cortex ReduceOnly).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Cortex stress signal clears",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_FEE_MODEL_HARD_STALE: ModeReasonMeta(
        display="Fee model hard-stale (cannot trust edge calculations).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Fee model refreshed within staleness threshold",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_RISKSTATE_DEGRADED: ModeReasonMeta(
        display="RiskState is Degraded (system protecting capital).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="RiskState returns to Healthy",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_POLICY_STALE: ModeReasonMeta(
        display="Policy is stale (no trading on old policy).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Policy refreshed within staleness threshold",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_MARGIN_MM_UTIL_HIGH: ModeReasonMeta(
        display="Margin utilization high (reduce only).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="mm_util < 0.80 for >= 60s",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_INPUT_MISSING_OR_STALE: ModeReasonMeta(
        display="Critical input missing/stale (fail-closed).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="All required inputs fresh",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_WATCHDOG_UNCONFIRMED: ModeReasonMeta(
        display="One watchdog corroboration signal missing (fail-closed).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="All watchdog signals confirmed",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_DISK_KILL_UNCONFIRMED: ModeReasonMeta(
        display="Disk kill predicate unconfirmed (fail-closed).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Disk predicate confirmed safe",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
    ModeReasonCode.REDUCEONLY_SESSION_KILL_UNCONFIRMED: ModeReasonMeta(
        display="Session kill predicate unconfirmed (fail-closed).",
        latched=False,
        unblock=UnblockMeta(
            unblock_type="AUTO",
            condition="Session predicate confirmed safe",
        ),
        tier=TradingMode.REDUCE_ONLY,
    ),
}

OPEN_PERMISSION_REASON_CODES: Final[frozenset[str]] = frozenset(
    item.value for item in OpenPermissionReasonCode
)

DECISION_A_LATCH_REASON: Final[str] = ModeReasonCode.REDUCEONLY_OPEN_PERMISSION_LATCHED.value
