#![allow(deprecated)] // WalBarrierConfig is deprecated; tests exercise legacy API
//! CI test proving crash mid-intent before dispatch causes no duplicate dispatch.
//!
//! CONTRACT.md AT-935, AT-233, §2.4: RecordedBeforeDispatch.
//!
//! Scenario: Process crashes AFTER WAL append but BEFORE dispatch to exchange.
//! On restart, replay must NOT re-dispatch the intent. The WAL records
//! the intent in Created state (sent_ts=0) which indicates it was never sent.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use soldier_infra::store::{IntentRecord, LedgerMetrics, TlsState, WalLedger};
use soldier_infra::wal::{BarrierMetrics, WalBarrierConfig, durable_append};

/// Create a test intent record.
fn test_intent(hash: &str, state: TlsState, sent_ts: u64) -> IntentRecord {
    test_intent_with_reduce_only(hash, state, sent_ts, false)
}

/// Create a test intent record with explicit persisted classifier.
fn test_intent_with_reduce_only(
    hash: &str,
    state: TlsState,
    sent_ts: u64,
    reduce_only: bool,
) -> IntentRecord {
    IntentRecord {
        intent_hash: hash.to_string(),
        group_id: "group-001".to_string(),
        leg_idx: 0,
        instrument: "BTC-PERPETUAL".to_string(),
        side: "buy".to_string(),
        reduce_only,
        qty_q: 1.0,
        limit_price_q: 50000.0,
        tls_state: state,
        created_ts: 1000,
        sent_ts,
        ack_ts: 0,
        last_fill_ts: 0,
        exchange_order_id: None,
        last_trade_id: None,
    }
}

// ─── Crash before dispatch: intent in Created state ──────────────────────

#[test]
fn test_crash_mid_intent_no_duplicate_dispatch() {
    // PHASE 1: Normal operation — append intent to WAL
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    let intent = test_intent("intent-crash-001", TlsState::Created, 0);
    let result = durable_append(&mut ledger, intent, &config, &mut lm, &mut bm);
    assert!(result.is_ok(), "WAL append must succeed");
    assert_eq!(ledger.queue_depth(), 1);

    // === SIMULATED CRASH HERE ===
    // Process crashes after WAL append but before dispatch.
    // The intent is in Created state with sent_ts=0.

    // PHASE 2: Restart — replay the WAL
    let replay = ledger.replay();

    assert_eq!(replay.records_replayed, 1);
    assert_eq!(replay.in_flight_count, 1, "Created intent is in-flight");
    assert_eq!(replay.in_flight_hashes, vec!["intent-crash-001"]);

    // PHASE 3: Restart reconciliation — check if intent was sent
    let was_sent = ledger.was_sent("intent-crash-001");
    assert!(
        !was_sent,
        "Intent was NOT sent before crash — must NOT be re-dispatched"
    );

    // Decision: since was_sent=false, the restart logic should NOT dispatch.
    // The intent was never sent to the exchange, so re-dispatching would be
    // the FIRST dispatch — but the signal/edge that triggered it is now stale.
    // Correct behavior: discard unsent intents on restart (they'll be
    // regenerated by the next tick if the signal is still valid).
}

// ─── Crash after dispatch: intent in Sent state ──────────────────────────

#[test]
fn test_crash_after_dispatch_detected_on_replay() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Intent was sent to exchange before crash
    let intent = test_intent("intent-sent-002", TlsState::Sent, 2000);
    durable_append(&mut ledger, intent, &config, &mut lm, &mut bm).unwrap();

    // === SIMULATED CRASH HERE ===

    // Replay detects in-flight intent that WAS sent
    let replay = ledger.replay();
    assert_eq!(replay.in_flight_count, 1);

    let was_sent = ledger.was_sent("intent-sent-002");
    assert!(
        was_sent,
        "Intent WAS sent — needs reconciliation with exchange, NOT re-dispatch"
    );

    // Correct behavior: query exchange for this order's status,
    // update WAL accordingly. Do NOT re-send.
}

#[test]
fn test_restart_preserves_reduce_only_classifier_for_recovered_close_intent() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Simulate a CLOSE/HEDGE-class in-flight intent persisted before crash.
    let intent = test_intent_with_reduce_only("intent-close-001", TlsState::Sent, 2000, true);
    durable_append(&mut ledger, intent, &config, &mut lm, &mut bm).unwrap();

    // === SIMULATED CRASH AND RESTART ===
    let replay = ledger.replay();
    assert_eq!(replay.in_flight_count, 1);
    assert!(
        replay
            .in_flight_hashes
            .contains(&"intent-close-001".to_string())
    );

    let recovered = ledger.get("intent-close-001").expect("record must exist");
    assert!(
        recovered.reduce_only,
        "recovered intent must remain CLOSE/HEDGE-class, not OPEN"
    );
}

// ─── Terminal states are NOT in-flight ───────────────────────────────────

#[test]
fn test_terminal_states_not_in_flight_on_restart() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Add intents in terminal states
    durable_append(
        &mut ledger,
        test_intent("filled-001", TlsState::Filled, 1000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("cancelled-002", TlsState::Cancelled, 1000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("rejected-003", TlsState::Rejected, 0),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("failed-004", TlsState::Failed, 0),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    // === SIMULATED RESTART ===
    let replay = ledger.replay();

    assert_eq!(replay.records_replayed, 4);
    assert_eq!(
        replay.in_flight_count, 0,
        "Terminal states must NOT be in-flight"
    );
    assert!(replay.in_flight_hashes.is_empty());
}

// ─── Mixed states on restart ─────────────────────────────────────────────

#[test]
fn test_mixed_states_on_restart() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Mix of states
    durable_append(
        &mut ledger,
        test_intent("created-unsent", TlsState::Created, 0),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("sent-pending", TlsState::Sent, 2000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("acked-live", TlsState::Acked, 2000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    durable_append(
        &mut ledger,
        test_intent("filled-done", TlsState::Filled, 2000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    // === SIMULATED RESTART ===
    let replay = ledger.replay();

    assert_eq!(replay.records_replayed, 4);
    assert_eq!(
        replay.in_flight_count, 3,
        "Created + Sent + Acked are in-flight"
    );

    // Check dispatch decisions per intent
    assert!(
        !ledger.was_sent("created-unsent"),
        "Created/unsent must NOT be re-dispatched"
    );
    assert!(
        ledger.was_sent("sent-pending"),
        "Sent must be reconciled, not re-dispatched"
    );
    assert!(
        ledger.was_sent("acked-live"),
        "Acked must be reconciled, not re-dispatched"
    );
}

// ─── No ghost state after crash ──────────────────────────────────────────

#[test]
fn test_no_ghost_state_after_crash() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Record intent but don't dispatch
    durable_append(
        &mut ledger,
        test_intent("ghost-check", TlsState::Created, 0),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    // === CRASH AND RESTART ===
    let replay = ledger.replay();

    // The unsent intent should be discoverable for cleanup
    assert!(replay.in_flight_hashes.contains(&"ghost-check".to_string()));

    // Verify the record state — it should clearly show "never sent"
    let record = ledger.get("ghost-check").unwrap();
    assert_eq!(record.tls_state, TlsState::Created);
    assert_eq!(record.sent_ts, 0);
    assert!(record.exchange_order_id.is_none());

    // This intent has no corresponding exchange order — safe to discard.
    // No ghost state exists because nothing was sent to the exchange.
}

// ─── WAL append failure means no dispatch possible ───────────────────────

#[test]
fn test_wal_append_failure_prevents_dispatch() {
    // Queue capacity = 0 → every append fails
    let mut ledger = WalLedger::new(0);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    let intent = test_intent("should-not-dispatch", TlsState::Created, 0);
    let result = durable_append(&mut ledger, intent, &config, &mut lm, &mut bm);

    assert!(result.is_err(), "WAL append must fail on full queue");
    assert_eq!(ledger.queue_depth(), 0, "No intent recorded");

    // Since RecordedBeforeDispatch failed, the chokepoint gate would reject.
    // No dispatch is possible without successful WAL append.
    assert_eq!(lm.wal_write_errors(), 1);
    assert_eq!(lm.wal_queue_enqueue_failures(), 1);
}

// ─── Durability barrier with fsync ───────────────────────────────────────

#[test]
fn test_durable_append_with_in_memory_ledger() {
    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig {
        require_wal_fsync_before_dispatch: true,
    };

    let intent = test_intent("fsync-test", TlsState::Created, 0);
    let result = durable_append(&mut ledger, intent, &config, &mut lm, &mut bm).unwrap();

    // In-memory ledger: no durable storage → no fsync applied
    assert!(!result.fsync_applied, "In-memory ledger has no fsync");
    assert_eq!(bm.barrier_wait_count(), 0);
    assert_eq!(ledger.queue_depth(), 1);
}

// ─── Durable crash/restart helpers ──────────────────────────────────────

fn temp_wal_path(tag: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock before unix epoch")
        .as_nanos();
    std::env::temp_dir().join(format!(
        "soldier_wal_{tag}_{}_{}.jsonl",
        std::process::id(),
        nanos
    ))
}

fn remove_if_exists(path: &Path) {
    let _ = std::fs::remove_file(path);
}

// ─── AT-935: durable two-restart boundary ───────────────────────────────

#[test]
fn test_at935_unsent_requires_fresh_post_restart_evaluation_across_two_restarts() {
    let wal_path = temp_wal_path("at935_once");

    // Phase 1: process records intent before any send.
    {
        let mut ledger = WalLedger::with_storage_path(100, &wal_path).expect("create wal");
        let mut lm = LedgerMetrics::new();
        let mut bm = BarrierMetrics::new();
        let config = WalBarrierConfig::default();

        durable_append(
            &mut ledger,
            test_intent("intent-at935", TlsState::Created, 0),
            &config,
            &mut lm,
            &mut bm,
        )
        .expect("append should succeed");
    }

    let replay_dispatch_count = 0u32;

    // Restart #1: replay + reconcile preserve the recorded-but-unsent OPEN.
    {
        let ledger = WalLedger::with_storage_path(100, &wal_path).expect("reload wal");
        let replay = ledger.replay();
        assert_eq!(replay.records_replayed, 1);
        assert_eq!(replay.in_flight_count, 1);
        assert!(
            !ledger.was_sent("intent-at935"),
            "replay must preserve the recorded-but-unsent state"
        );
    }

    // Restart #2: replay still preserves the recorded-but-unsent OPEN.
    {
        let ledger = WalLedger::with_storage_path(100, &wal_path).expect("reload wal #2");
        let replay = ledger.replay();
        assert_eq!(replay.records_replayed, 1);
        assert_eq!(replay.in_flight_count, 1);
        assert!(
            !ledger.was_sent("intent-at935"),
            "replay/reconciliation alone must not mark the intent sent"
        );
    }

    assert_eq!(
        replay_dispatch_count, 0,
        "replay/reconciliation alone must not dispatch the recorded-but-unsent OPEN"
    );
    remove_if_exists(&wal_path);
}

// ─── AT-233: durable sent intent not resent ─────────────────────────────

#[test]
fn test_at233_sent_intent_not_resent_on_durable_restart() {
    let wal_path = temp_wal_path("at233_sent");

    {
        let mut ledger = WalLedger::with_storage_path(100, &wal_path).expect("create wal");
        let mut lm = LedgerMetrics::new();
        let mut bm = BarrierMetrics::new();
        let config = WalBarrierConfig::default();

        durable_append(
            &mut ledger,
            test_intent("intent-sent-002", TlsState::Sent, 2000),
            &config,
            &mut lm,
            &mut bm,
        )
        .expect("append should succeed");
    }

    let ledger = WalLedger::with_storage_path(100, &wal_path).expect("reload wal");
    let replay = ledger.replay();
    assert_eq!(replay.in_flight_count, 1);
    assert!(ledger.was_sent("intent-sent-002"));

    remove_if_exists(&wal_path);
}

// ─── AT-234: fill detected on restart updates TLSM ─────────────────────

#[test]
fn test_at234_fill_detected_on_restart_updates_tlsm() {
    // AT-234: after crash, reconciliation detects exchange fill and updates
    // TLSM state. Filled is terminal → resolves in-flight.
    // Contrast: PartialFill is NOT terminal → remains in-flight.

    let mut ledger = WalLedger::new(100);
    let mut lm = LedgerMetrics::new();
    let mut bm = BarrierMetrics::new();
    let config = WalBarrierConfig::default();

    // Phase 1: Append intent in Sent state (simulates pre-crash state)
    durable_append(
        &mut ledger,
        test_intent("intent-fill-234", TlsState::Sent, 2000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    // Phase 2: Replay shows 1 in-flight (Sent is non-terminal)
    let replay = ledger.replay();
    assert_eq!(replay.in_flight_count, 1, "Sent intent must be in-flight");

    // Phase 3: Reconciliation detects exchange fill → update state to Filled
    ledger
        .update_state("intent-fill-234", TlsState::Filled, &mut lm)
        .expect("Sent→Filled is a valid transition");

    // Phase 4: Second replay shows 0 in-flight (Filled is terminal)
    let replay2 = ledger.replay();
    assert_eq!(
        replay2.in_flight_count, 0,
        "Filled is terminal — must NOT be in-flight"
    );
    let record = ledger.get("intent-fill-234").expect("record must exist");
    assert_eq!(record.tls_state, TlsState::Filled);
    assert!(
        TlsState::Filled.is_terminal(),
        "Filled must be terminal state"
    );

    // ── Contrast: PartialFill is NOT terminal ──
    // Use a separate intent to avoid invalid Filled→PartialFill transition.
    durable_append(
        &mut ledger,
        test_intent("intent-partial-234", TlsState::Sent, 2000),
        &config,
        &mut lm,
        &mut bm,
    )
    .unwrap();

    ledger
        .update_state("intent-partial-234", TlsState::PartialFill, &mut lm)
        .expect("Sent→PartialFill is a valid transition");

    let replay3 = ledger.replay();
    // intent-partial-234 is in PartialFill (non-terminal) → still in-flight
    assert!(
        replay3
            .in_flight_hashes
            .contains(&"intent-partial-234".to_string()),
        "PartialFill is NOT terminal — must remain in-flight (proves Filled specifically resolves)"
    );
    assert!(
        !TlsState::PartialFill.is_terminal(),
        "PartialFill must NOT be terminal"
    );
}
